### ISSUE TITLE
OAuth never granted - Authorizing Tree spins forever

### ISSUE THREAD

**Issue by bluntcoder** [NirmalScaria/le-git-graph#75] opened 2024-05-12 19:26 UTC
**Describe the bug**
Tried to authorize to use Le Git Graph, window spins forever

**Expected behavior**
OAuth is authorized, and I can use the plugin.

**Screenshots**
![image](https://github.com/NirmalScaria/le-git-graph/assets/2693220/477427fe-8773-45dd-926b-4f665c967636)

Inspecting the code I have this in the Chrome inspector:

```
Failed to load resource: the server responded with a status of 500 ()
authorize/:1 Uncaught (in promise) SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON
    at JSON.parse (<anonymous>)
    at script.js:16:33
    at async sendAuthorisationRequestv2 (script.js:15:5)
authorize/:1 Uncaught (in promise) Error: 400: Invalid Token
    at tA (chrome-extension://difoiogjjojoaoomphldepapgpbgkhkb/background.js:5:17783)
    at async chrome-extension://difoiogjjojoaoomphldepapgpbgkhkb/background.js:1:62729
```

**Comment by NirmalScaria** [comment] 2024-06-05 18:57
Hey,
Thank you for reporting. The issue was caused by issues on the OAuth server. I forgot to check the billing status of the server and the account got suspended. It is resolved now.
Closing the issue for now. It should be fixed by now. Feel free to reopen if the issue persists.

**Comment by barzan-hayati** [comment] 2024-08-31 07:38
I also have this issue when I want to check commits for specific repo.

**Comment by NirmalScaria** [comment] 2024-09-01 18:21
Fixed it.

**Closed by NirmalScaria** 2024-09-01 18:21 UTC
Labels: bug

**Comment by barzan-hayati** [comment] 2024-09-01 20:29
> Fixed it.

Let me check it

**Comment by barzan-hayati** [comment] 2024-09-01 20:52
> Fixed it

Does not work on Firefox and Chrome.

**Comment by GribanovIvan** [comment] 2025-03-05 23:48
I can confirm on Firefox
