### ISSUE TITLE
Branches in git graph are of same color (Red color with two concentric circles)

### ISSUE THREAD

**Issue by thefirehacker** [NirmalScaria/le-git-graph#5] opened 2022-11-01 07:14 UTC
**Describe the bug**
Branches in git graph and legend on top right are all of same color. As a result its not possible to differentiate the branch in git graph and this impacts visualization.

**To Reproduce**
1. Go to 'https://github.com/tensorflow/tensorflow'
2. Ensure that the chrome extension is enabled and page is refreshed so that commit tab appears on github.
3. Click on 'commits'

**Expected behavior**
3 Branch should have different color in legend (top right) and same color should be shown on git graph too.

**Screenshots**

 ![Legend](https://user-images.githubusercontent.com/32054618/199178921-d1979cf1-c54b-459c-97bb-07a3fbfb444c.png)

![GitGraph](https://user-images.githubusercontent.com/32054618/199179003-86594611-1408-4d79-8f7d-a9f7e80d1715.png)

**Desktop (please complete the following information):**
 - OS: [. Windows 11]
 - Browser [chrome Version 106.0.5249.120]

**Comment by adssidhu86** [comment] 2022-11-01 07:16
This is an inconsistent issue , closing this issue now . Will reopen once  its reproduced.
I suspect that color for each branch is chosen at random and in some cases all colors are appearing red,

**Comment by NirmalScaria** [comment] 2022-11-01 11:38
I was also able to reproduce the issue, in multiple repositories.

As of now, there are 9 colours defined for the branches/commits/legends. The problem is that these colours are not assigned in an optimal way. There is a strong bias towards red and blue.

Solving this issue will not only avoid the confusions, but provide a better visual experience too IMO.

**Comment by adssidhu86** [comment] 2022-11-02 07:12
Great I will take a crack at fixing this issue too :) .

**Comment by NirmalScaria** [comment] 2022-11-15 14:05
[UPDATE] 
I was able to find out what exactly goes wrong here. The algorithm to assign colours assigns colours in the order of, from newer commits to older commits. It keeps assigning the same colour as the child commit in most cases. And, a new colour is assigned only when either branching occurs, or when a child-less commit is found (which is rightly assumed to be the head of some branch). 
The problem with that approach is that, there could be commits which are head of some branch, but yet, not falling to either of the above categories. That results in two heads having same colour, and hence this issue. 
So, a new manual check should be implemented to check if the commit is the head of some branch, while assigning colours. That should fix this issue.

**Comment by NirmalScaria** [comment] 2022-11-25 21:59
[UPDATE]
This has been fixed. Along with improvements in the algorithm to assign colours... 😄

**Closed** 2022-11-25 21:59 UTC
Labels: bug
